### ISSUE TITLE
[Fatal] System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by CipherArrow** [YewYew/Attributer#1]
The below error message is filling up my server log file like crazy and this length of code never changes regarding what line it's saying issues are being resolved at.

Version of Vintage Story: 1.18.12; however, it was also doing this for me in 1.18.10.

```
19.9.2023 00:00:39 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at attributer.src.patch.WearableStatsPatch.handleDamagedWearableStats(IPlayer player, Single damage, DamageSource dmgSource, ICoreAPI& ___api, Single& __result) in C:\Users\Yew\AppData\Roaming\.vintagestory\vscmods\vsmodtemplate-1.5.8\mods-dll\attributer\src\patch\WearableStatsPatch.cs:line 217
   at Vintagestory.GameContent.ModSystemWearableStats.handleDamaged_Patch2(ModSystemWearableStats this, IPlayer player, Single damage, DamageSource dmgSource)
   at Vintagestory.GameContent.ModSystemWearableStats.<>c__DisplayClass8_0.<Event_PlayerJoin>b__1(Single dmg, DamageSource dmgSource) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WearableStats.cs:line 67
   at Vintagestory.GameContent.EntityBehaviorHealth.OnEntityReceiveDamage(DamageSource damageSource, Single& damage) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Entity\Behavior\BehaviorHealth.cs:line 168
   at Vintagestory.API.Common.Entities.Entity.ReceiveDamage(DamageSource damageSource, Single damage) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Entity\Entity.cs:line 791
   at Vintagestory.API.Common.EntityAgent.ReceiveDamage_Patch1(EntityAgent this, DamageSource damageSource, Single damage)
   at Vintagestory.GameContent.AiTaskMeleeAttack.attackTarget() in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Entity\AI\Task\TasksImpl\AiTaskMeleeAttack.cs:line 161
   at Vintagestory.GameContent.AiTaskMeleeAttack.ContinueExecute(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Entity\AI\Task\TasksImpl\AiTaskMeleeAttack.cs:line 151
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Entity\AI\Task\AiTaskManager.cs:line 174
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VSEssentials\Entity\AI\Task\BehaviorTaskAI.cs:line 116
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Entity\Entity.cs:line 852
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Entity\EntityAgent.cs:line 528
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 326
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 165
   at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 881
```

**Comment by CipherArrow** [comment]
Still getting this in 1.18.13. By the way, I only have the attributer installed of your mods and not your RPG Item Rarity mod if it helps narrow things down.

**Comment by WickedSchnitzel** [comment]
Getting this as well. Please fix.
